name: tests-tickets

on:
  pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd tickets && npm install -g pnpm && pnpm i && pnpm run test:ci
